name: Eslint & Mocha test check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    defaults:
      run:
        working-directory: ./CAScript-node-js-runtime

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Mocha Tests
        path: test-results.json
        reporter: mocha-json