name: Eslint & Mocha test check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run eslint
    - name: Code coverage-reporter
      uses: tj-actions/coverage-reporter@v3
      with:
        coverage-command: "nyc --reporter=text mocha -r ts-node/register test/**/*.ts"
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ./**/*.xml